### ISSUE TITLE
Is this compatible with the official release?

### ISSUE THREAD

**Issue by TheWitheredStriker** [rewrking/DynRPG#5]
Hello, hoping you are well.

I am aware that the original version of DynRPG, as developed by Cherry, is not compatible with the official 2015 release of RPG Maker 2003. However, this seems to be an updated fork of DynRPG that has received updates quite recently. I wanted to ask if this version of DynRPG works with the legal RM2k3, or if it is stuck on the fan translations just like the original one? Asking because Cherry [implied](https://forums.rpgmakerweb.com/index.php?threads/plugins-for-rpg-maker-2k3.137110/post-1191821) that a port to the official version of 2k3 may be in the works (though it may possibly never be completed), so this garnered my curiosity.

**Comment by CherryDT** [comment]
ManDeJan and a friend of his had a go at porting it but it turned out too big a project. As far as I know it's on ice.

This repo has sources for the library and all the headers including Andrew's improvements, but the sources of the other parts of DynRPG beyond the library (patch, patcher, DLL) can be found in [my own DynRPG repo](https://github.com/CherryDT/DynRPG), so in theory other people could attempt to build such a port too. It is however really quite a complex feat so I don't have high hopes...

**Comment by TheWitheredStriker** [comment]
Thank you for the response, Cherry!

Porting DynRPG to the official release is a pipe dream of mine, and within several years I might attempt it. But I'm not getting my hopes _too_ high up either; I'll definitely try, but I do not expect it to just work. 

We shall see what the future holds. In any event, I hope you are well, and wanted to thank you again for the (very quick) answer.

**Comment by rewrking** [comment]
Yeah, with this, you're locked into v1.08 of the unofifically translated RPG Make 2003. This repo just has the C++ sources to build a new DynRPG.dll and has all of the updated headers written by myself and bugmenot (not sue where he still posts though). This repo also has a CMakeLists.txt to make building it pretty easy in any version of MinGW.
